library(plyr)
library(datasets)
tabAll <- read.table("./A1/household_power_consumption.txt", header = TRUE,sep = ";", colClasses = "character", stringsAsFactors=FALSE)
interval <- subset(tabAll, tabAll[, 1] == "1/2/2007" | tabAll[, 1] == "2/2/2007")
interval[, 1] <- as.Date(interval[, 1], "%d/%m/%Y")
study <-mutate(interval,DT=paste(Date,Time,sep=" "))
study[[10]] <- strptime(study[[10]], "%Y-%m-%d %H:%M:%S", tz = "")
study[, 3] <- as.numeric(study[, 3])
df <- subset(study, select = c(10, 3))
plot(df, type = "l", xlab ="",  ylab = "Global Active Power (kilowatts)")
dev.copy(png, file = "plot2.png", bg = "transparent")
dev.off()