library(plyr)
library(datasets)
tabAll <- read.table("./A1/household_power_consumption.txt", header = TRUE,sep = ";", colClasses = "character", stringsAsFactors=FALSE)
interval <- subset(tabAll, tabAll[, 1] == "1/2/2007" | tabAll[, 1] == "2/2/2007")
interval[, 1] <- as.Date(interval[, 1], "%d/%m/%Y")
study <-mutate(interval,DT=paste(Date,Time,sep=" "))
study[[10]] <- strptime(study[[10]], "%Y-%m-%d %H:%M:%S", tz = "")
study[, 7] <- as.numeric(study[, 7])
study[, 8] <- as.numeric(study[, 8])
study[, 9] <- as.numeric(study[, 9])
df <- subset(study, select = c(10, 7, 8, 9))
plot(df$DT, df$Sub_metering_1, type = "l", ylim = c(0, 40), col = "gray", xlab ="", ylab = "Energy sub metering")
points(df$DT, df$Sub_metering_2, type = "l", col = "orangered3")
points(df$DT, df$Sub_metering_3, type = "l", col = "blue")
legend("topright", pch = c(NA, NA, NA), ncol = 1, col = c("gray", "orangered3", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd =2)
dev.copy(png, file = "plot3.png", bg = "transparent")
dev.off()